services:
  - type: web
    name: diamond-ace
    env: php
    buildCommand: |
      apt-get update && apt-get install -y php-cli unzip curl
      curl -sS https://getcomposer.org/installer | php
      mv composer.phar /usr/local/bin/composer
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: RENDER_PHP_VERSION
        value: 8.1
